Run smoke test on staging

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -1,34 +1,33 @@
 ---
 
-name: Tests
+name: Deployment
+run-name: Deployment ${{ github.event.deployment_status.state }} on ${{ github.event.deployment.environment }} by ${{ github.actor }}
 
 on:
-  pull_request:
-    branches: ['*']
+  deployment_status:
+
+env:
+  URL: ${{ github.ref_name == 'main' && 'https://resume-staging.frankel.dev' || github.ref_name == 'prod' && 'https://resume.frankel.dev' || '' }}
 
 jobs:
-  test:
+  status_update:
     runs-on: ubuntu-latest
-    continue-on-error: false
+    steps:
+      - name: Event payload
+        run: |
+          echo "${{ toJson(github.event) }}"
+      - name: Fail job if deployment failed
+        if: ${{ github.event.deployment_status.state == 'failure' }}
+        run: |
+          echo "Deployment failed"
+          exit 1
+
+  smoke-test:
+    runs-on: ubuntu-latest
+    needs: status_update
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-
-      - name: Install pulumi
-        uses: pulumi/actions@v4
-        with:
-          pulumi-version: 3.154.0
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-
-      - name: Install uv
-        uses: astral-sh/setup-uv@v4
-
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version-file: ".python-version"
 
       - name: Set up NodeJS
         uses: actions/setup-node@v4
@@ -37,18 +36,6 @@ jobs:
 
       - name: Install npm dependencies
         run: npm install -g pnpm && pnpm install
-
-      - name: Install the Python project
-        run: uv sync --all-extras --dev
-
-      - name: Start containers
-        run: make docker-up
-
-      - name: Pulumi up
-        run: make pulumi-up
-
-      - name: Run integration tests
-        run: make pytest
 
       - name: Get installed Playwright version
         id: playwright-version
@@ -69,7 +56,7 @@ jobs:
         if: steps.playwright-cache.outputs.cache-hit != 'true'
 
       - name: Run Playwright tests
-        run: pnpm exec playwright test
+        run: URL=$URL pnpm exec playwright test
 
       - uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
